### ISSUE TITLE
duplicating last line in .cfg parser

### ISSUE THREAD

**Issue by NoahTheLegend** [transhumandesign/kag-base#1924] opened 2024-02-24 21:38 UTC
**Description**

.cfg files (as i presume, with array in last element) that do not have empty line following after last semicolon will parse last line twice
in example:

![image](https://github.com/transhumandesign/kag-base/assets/76755422/41ead115-c952-49d9-b28c-1501beea2622)
we have a problematic map that is used to appear twice as often in one mapcycle here

![image](https://github.com/transhumandesign/kag-base/assets/76755422/2afbf27d-dfff-46eb-aa4a-2d3e437b9f59)
but now, if we add an empty line after, it should be fixed and act normally

the bug was found by @GoldenGuy  and seems to be present in _every_ config file that has some array in its ending
I may be wrong in my statements but you can test complexier if you want

**Expected Behavior**

Either fix the engine parser or investigate base \ yourmod code and fix it by urself

**Additional context**

amogus

**Comment by asumagic** [comment] 2024-02-25 14:38
Closing as duplicate of #199, indeed never got fixed

**Closed by asumagic** 2024-02-25 14:38 UTC
