### ISSUE TITLE
Make health bar that shows under players script side

### ISSUE THREAD

**Issue by CatWiz** [transhumandesign/kag-base#976] opened 2020-12-12 15:19 UTC
Title. There is HealthBar.as but the only thing it does as far as i can tell is draw rectangles. Also let everyone see enemy health from any distance, currently this gameplay advantage is given only to admins for some reason.

**Comment by AsuMagic** [comment] 2021-11-10 10:24
Duplicate of #282

**Closed by AsuMagic** 2021-11-10 10:24 UTC
Labels: change, engine change
