### ISSUE TITLE
Allow for CSprite & CSpriteLayer image angle Getting and Setting

### ISSUE THREAD

**Issue by Olimarrex** [transhumandesign/kag-base#117] opened 2018-05-31 11:56 UTC
A request to add 2 functions / methods for CSprites and CSpriteLayers that allows you to read and set the image angle of the sprite without having to go use ResetTransform() and RotateBy().

This gives programmers more control over the rotation of the image & sprite layers without having to reset the image scale of an object.

You can work around this by storing a new variable that remembers the angle, then have it so that whenever it is changed, you rotate the image by the difference in amount every time.

**Comment by Harrison-Miller** [comment] 2020-02-11 16:50
Closing this since it's essentially a duplicate of a ticket with more discussion and they have the same goal: https://github.com/transhumandesign/kag-base/issues/117

**Closed by Harrison-Miller** 2020-02-11 16:50 UTC
Labels: engine change
