### ISSUE TITLE
team switching menu sometimes disappears when trying to switch team

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#93] opened 2018-04-10 20:56 UTC
sometimes when I open my menu and try to switch teams the team switching menu disappears which requires me to reopen it several times.

I don't think this is a bug with the engine as much as it is with the script

I think the team switching menu should stay open until clicked out of

**Comment by 1bardesign** [comment] 2018-04-11 01:51
I think this happens as a result of the click "passing through" the menu as it gets closed, so unless you click quickly it's possible to end up closing the menu right after opening it. I'll look into it but it's not particularly high priority.

It'd be possible to build a separate menu based on the event, but as far as I've seen this affects all grid menu based team swap solutions (ie all vanilla ones + modded ones based on them)

**Comment by Harrison-Miller** [comment] 2020-02-14 04:09
Duplicate of this: https://github.com/transhumandesign/kag-base/issues/586

**Closed by Harrison-Miller** 2020-02-14 04:09 UTC
Labels: bug
