### ISSUE TITLE
placed seeds won't collapse

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#606] opened 2019-06-12 07:20 UTC
You can place seeds on (or above, next to or below) background for some reason.

When the background (or whatever the seed is placed on) collapses, the seeds will not collapse but remain in the air.

**Comment by Harrison-Miller** [comment] 2020-02-11 05:28
Can you provide a video?

**Comment by AsuMagic** [comment] 2020-02-11 08:19
It's fairly easy to reproduce: 
![placing on wooden backwall](https://user-images.githubusercontent.com/8986152/74220267-6a9ec800-4caf-11ea-958e-c0f04bef66f7.png)
![collapsing wooden backwall](https://user-images.githubusercontent.com/8986152/74220278-71c5d600-4caf-11ea-8c46-b8307209ce59.png)
Looks like it should check whether there is a dirt background rather than just a regular background. I'm not sure where this is handled but make sure you don't break placing stuff on backwalls (e.g. spikes) when intended.

**Comment by Panky123** [comment] 2020-02-11 13:29
If you leave the seeds floating too long they also despawn. Really old bug that would be a pleasant surprise to see fixed.

**Comment by eps0003** [comment] 2020-09-25 05:17
Fixed in #856

**Closed by eps0003** 2020-09-25 05:17 UTC
Labels: bug, good first issue
